//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egzemplioriu
    {
        public int Id { get; set; }
        public int Isbn { get; set; }
        public Nullable<int> Skaitytojas { get; set; }
        public Nullable<System.DateTime> Gražinimo_laikas { get; set; }
    
        public virtual Knygos Knygo { get; set; }
        public virtual Vartotojai Vartotojai { get; set; }
    }
}
