//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vartotojai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vartotojai()
        {
            this.Egzempliorius = new HashSet<Egzemplioriu>();
        }
    
        public int Id { get; set; }
        public string Prisijungimo_vardas { get; set; }
        public string Slaptazodis { get; set; }
        public int DarbSkait { get; set; }
        public string Vardas { get; set; }
        public Nullable<int> Telefono_numeris { get; set; }
        public string Adresas { get; set; }
        public Nullable<int> Pasto_Kodas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egzemplioriu> Egzempliorius { get; set; }
    }
}
